---
- name: kubeadm | copy repo
  copy: src=kubernetes.repo dest=/etc/yum.repos.d/


- name: kubeadm | disable selinux
  selinux:
    policy: targeted
    state: disabled
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


- name: kubeadm | Disable swap
  shell: swapoff -a
  when: ansible_swaptotal_mb > 0


- name: kubeadm | Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent


- name: kubeadm | install kubeadm components
  yum:
    name:
      - "kubelet-{{ kubernetes_version }}"
      - "kubeadm-{{ kubernetes_version }}"
      - "kubectl-{{ kubernetes_version }}"
    disable_excludes: kubernetes
    state: present

- name: kubeadm | enable kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes


- name: kubeadm | sysctl conf
  copy: src=k8s.conf dest=/etc/sysctl.d/
  register: k8s_sysctl


- name: kubeadm | sysctl apply
  shell: sysctl --system
  when: k8s_sysctl.changed


- name: kubeadm | pull images
  shell: "kubeadm config images pull --kubernetes-version v{{ kubernetes_version }}"
  when:
    - "'master' in group_names"
    - kubernetes_pull_images| bool
